### ISSUE TITLE
Usability: Sliders in "Atlasing Controller" only work if the sliders themself are moved, not if you click in the sliders range.

### ISSUE THREAD

**Issue by mwawra** [JingyiGF/HERBS#17]
Hello, I found small error in the GUI. I'm not sure how to explain it correctly.
If I'm moving the sliders in the "Atlasing Controller" (e.g. Opacity) directly they work fine, but if I move the sliders by clicking left or right of them the sliders themself move but the value right of the sliders is not changing and also the changes are not processed in the viewer.

**Comment by JingyiGF** [comment]
Thank you for the feedback. I will have a look and come back to you.

**Comment by JingyiGF** [comment]
Fixed in the newest version. Thanks again for the feedback. I will close the issue now.
