### ISSUE TITLE
unmerging 

### ISSUE THREAD

**Issue by vncntprvst** [JingyiGF/HERBS#21]
Hi,
I'm posting multiple issues, but I have to say this is a great software. Thanks for developing it!
At the moment, it doesn't seem possible to unmerge objects. Is that a feature that you plan to add at a later point? 
Thanks,
Vincent

**Comment by JingyiGF** [comment]
Hi Vincent, thank you for the comment on HERBS. I am glad that I can help in the field :-) about the unmerging, may I ask the purpose to do so? I never thought about it before. I have a long list about all kinds of requests. If you can convince me this is a useful feature, I am willing to modify the code and add it as a feature 😄

**Comment by vncntprvst** [comment]
Let me try to convince you then 😄 (and please let me know if we missed something). 
Registering labeled cells to the atlas is often a multi-rounds process. After completing the registration and reviewing the results, we usually find regions that require further adjustments (each brain is unique and deviate somewhat from the atlas). However, if the Cells objects have been merged, they cannot be updated (e.g, by deleting the faulty slices, doing a new alignment). Yet to view the cells in the 3D window, the individual Cells objects have to be merged. So, what we do at the moment is to save the project before merging, so that we can go back to the un-merged version. Having the option to un-merge would remove the need to use this workaround.

**Comment by JingyiGF** [comment]
Let me see. are you saying you want a functionality that after loading a merged cell object, you want to delete some of the cells from that object? According to the re-overlay images? that means you know which of the slices are wrong in the saved object, right? Do you usually match histological images to un-rotated atlas or rotated atlas? 

I mean you click cells on 2D images, after adding pieces, the 2D coordinates are already gone, instead 3D coordinates of cells are generated. To un-merge an object, I need to know how many steps I have to go back. but according to what you said, you are not trying to un-merge, but trying a way to modify the object, right? please correct me if I misunderstood you.

**Comment by vncntprvst** [comment]
> you want to delete some of the cells from that object? According to the re-overlay images?

> you are not trying to un-merge, but trying a way to modify the object, right? 

Yes, essentially, we're looking for a way to modify the 3D object. I understand this might be somewhat complicated to implement in HERBS. This request comes from our current workflow, where we can load and scroll through all the histology images from a given experiment. After doing the atlas registration and cell counting, if we find labeled regions that need adjusting, we can go back to those slices and modify either the registration or the cell marker location. In HERBS, I figured the way to do that would be to delete the corresponding 2D cell object and replace it. That is not an option if the cell objects are merged into a 3D object. 
Maybe what could be done is to allow users to preserve the 2D objects when merging, and just switch off their visibility? 

> Do you usually match histological images to un-rotated atlas or rotated atlas?

We first do the atlas registration (using the "_Matching Histological Images with the Atlas_" recipe), then we do the "_Cell Body registration_" step.

**Comment by JingyiGF** [comment]
hmmmm, I mean normally we assume the cutting plane (coronal, sagittal, horizontal) is perfect, but it is not always true. In HERBS users can do the virtual cutting by any angle on atlas, then match the histological images to the arbitrary angle cut atlas slice. I wonder when you match the histological images to the atlas slice, do you rotate the slice first and then match? Or totally no rotation on the cutting plane? I have to ask this, because if you match a histological image with rotated slice, you have to remember how you rotate the atlas slice, so that you can trace back which cells are from the same slice (if I make a cell object can be modified, but not undo merging). The 2D and 3D are related, I can go back and forth between these coordinates. But for 2D coordinates, there are a lot more different situations to consider about. So the more I know what you usually do, the easier for me to think about how to modify code.

**Comment by vncntprvst** [comment]
I see. We do rotate the slices, and keep records for each section. Something like this: 
```
Slice		AP (25um)		Coronal Left/Right angle	Coronal Top/Down angle
K3M2_1_1	396 (2775.98)	        8							0
K3M2_1_2	393 (3250)		8							0
```

**Comment by JingyiGF** [comment]
Thanks for the explanation, then either undo merging or modify cell objects. I have to think a bit more 'which is the best solution'. One thing needs to be noted, only recording the angle is not enough. So far I give users so much flexibility that the rotation origin is changing when you slicing through the atlas. The rotation origin is at the intersection of 3 planes when there is no rotation. so besides the angles, you have to record all AP, ML, DV page number.

**Comment by vncntprvst** [comment]
Sounds good. Happy to chat or provide more feedback if needed.

**Comment by JingyiGF** [comment]
Hi @vncntprvst , un-merging is on GitHub, not PyPI yet, but will be soon. The first button will do un-merging on a merged object. 

<img width="306" alt="Screenshot 2022-11-23 at 15 01 59" src="https://user-images.githubusercontent.com/64961126/203567465-d9cef683-0bd6-45dc-bd7e-d0122afbe8fa.png">

**Comment by JingyiGF** [comment]
Hi @vncntprvst, sorry for such a late reply. I finally updated the code on GitHub and PyPI. I will close this issue and please do open a new issue if there is something wrong or not clear!

Thank you for the interesting request and your clear explanation about the request. I wish you a happy holiday season and see you in 2023!
