### ISSUE TITLE
Issues with registering (triangulation) histology slices to atlas

### ISSUE THREAD

**Issue by nataliekoh** [JingyiGF/HERBS#23]
Hi Jingyi! I can now load my tif images in HERBS but I am having issues with registration. I am following the steps in the cookbook (sec 6.5.1) but I am not clear about a couple of things.

First, does it matter whether we move the triangulation points on the atlas first, or on the histology slice first? Can I move a hypothetical point 1 on the atlas and then the corresponding point 1 on the histology image, and then move hypothetical point 2 on the histology image and then point 2 on the atlas image (i.e. Point 1 atlas -> Point 1 histology -> Point 2 histology -> Point 2 atlas, etc.)? 

Second, I am not seeing any numbers next to the triangulation points like it shows in the cookbook [see screenshot 1]. When I click on the 'Transform to Atlas tool' button, you can see in screenshot 2 that there is no registration at all, and nothing in the histology slice is lined up with the atlas slice, even at the triangulation points. 

Third, when I click on the bounding box icon, I get an error on the bottom left of the GUI that says "No in-image triangulation points are selected" [see screenshot 3]. It also seems like all the border triangulation points are movable, unlike what it says in the cookbook. 

![pic1](https://user-images.githubusercontent.com/16214559/199647292-f446deb8-f168-4381-a1aa-76d6563ae40d.png)
![pic2](https://user-images.githubusercontent.com/16214559/199647299-1f86b193-6fd3-4717-ba7d-f35fbf1128c2.png)
![pic3](https://user-images.githubusercontent.com/16214559/199647703-e3d37be5-8263-42fc-b635-7f6d81ba624f.png)

Thank you again for your help!

**Comment by JingyiGF** [comment]
HI Natalie, Thanks for the update and issue report. could you please repeat each step you did, check if there is error message after each step, and make a screen shot after each step? I suspect there are some error messages before you select the points on the window. I could not tell what that is without your help. The more information I got, the easier for me to debug. For example, What type of histological image are you using? how many channels? what type of cleaning did you do to the image? I am also trying to reproduce the same situation. will see.

**Comment by nataliekoh** [comment]
Hi Jingyi, I am using a tif image. I first loaded a tif image with 3 channels (I had sent you an example previously), and then the atlas, and then I clicked on the triangulation tool. The error comes up when I click on the triangulation tool.

![pic4](https://user-images.githubusercontent.com/16214559/199807866-d47bb6b3-4b93-45da-8bd3-b7d186b598f1.png)

**Comment by JingyiGF** [comment]
Hei Natalie, thank you so much for the error message. The message says that the error comes when you change the number of triangulation points on the boundary of the image/atlas. When you delete the number 2, the text input will be empty string. This is not valid for the later calculation.  I fixed the text input value issues in the new version just now.

But I can not re-produce the same error as you mentioned
 > Second, I am not seeing any numbers next to the triangulation points like it shows in the cookbook [see screenshot 1].

I think probably you have other steps, or some combinations of button clicking that leads to this result. Again, I need your help to reproduce the same error to find the problem. 

And about 
> First, does it matter whether we move the triangulation points on the atlas first, or on the histology slice first? Can I move a hypothetical point 1 on the atlas and then the corresponding point 1 on the histology image, and then move hypothetical point 2 on the histology image and then point 2 on the atlas image (i.e. Point 1 atlas -> Point 1 histology -> Point 2 histology -> Point 2 atlas, etc.)?

It does not matter the order of points you move. you can move the points with any order you like. that means, you can move the points as you said, or you can move all the points in atlas window and then histological image window. But again, the text that indicates the order of points should be displayed. If they are not displayed, there must be some errors. I am trying to debug this.

**Comment by nataliekoh** [comment]
Hi Jingyi, thank you. I updated my HERBS but now I can't change the number of points - the 2 is fixed. I can add another digit to the 2, but I cannot change the number of points to 5 or 30, etc. 

There is no error message in the terminal or the GUI when I press the triangulation button. The points just show up, but they are not labeled. 

![pic5](https://user-images.githubusercontent.com/16214559/200007566-f38b466b-0198-4087-97d7-9171a825269e.png)

**Comment by JingyiGF** [comment]
what I always do is to select number 2, and type in the number I want without deleting the number first. 
<img width="405" alt="Screenshot 2022-11-04 at 16 30 31" src="https://user-images.githubusercontent.com/64961126/200014763-8405a7cb-af78-4655-9340-520b25c1be3c.png">

**Comment by nataliekoh** [comment]
Ah okay, that works. Thank you.

**Comment by nataliekoh** [comment]
Hi Jingyi, do you think that the reason the numbers aren't appearing is because I am using a TIFF image? Are you able to replicate the problem with the files I had shared with you?

**Comment by JingyiGF** [comment]
Hi Natalie,

I could not re-produce the same problem that the numbers are not displayed on both atlas and histological window. I would like to know your detail steps that lead to this problem. I also wonder if the numbers show up when you click points directly after loading the images. Many thanks for the help.

**Comment by JingyiGF** [comment]
This issue is solved by clicking points at desired locations on the image window instead of dragging boundary points to the desired locations. Please open new issues if there is further problems.
