### ISSUE TITLE
Python error after deleting layered histology image

### ISSUE THREAD

**Issue by torbenott** [JingyiGF/HERBS#3]
Minimal steps that reprouce error:

1. load atlas
2. load .tif histology image
3. Press the A in the menu bar (transform to atlas slice window)
4. delete the image in the layer view controller
5. Press the A in the menu bar again

No image layer is created and python error raised:

`C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py:4322: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  del_index = np.where(np.ravel(self.layer_ctrl.layer_link) == link_type)[0][0]
Traceback (most recent call last):
  File "C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py", line 3030, in transfer_to_atlas_clicked
    self.remove_single_link_related('atlas-overlay')
  File "C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py", line 4322, in remove_single_link_related
    del_index = np.where(np.ravel(self.layer_ctrl.layer_link) == link_type)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0`

**Comment by JingyiGF** [comment]
Thank you for your clear and valuable error message. Code updated both on GitHub and PyPI. Please let me know other errors. Many thanks again.

**Comment by torbenott** [comment]
thanks, it seems better but I'm running quite often into index errors after deleting objects. Another example would be after steps 1-3 from above, saving and loading the project, and then using delete either via 4 or 5

>>> import herbs
>>> herbs.run_herbs()
(71, 246, 653) bregma
image_changed
[  0   0 255 255]
add 0
Traceback (most recent call last):
  File "C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py", line 2776, in transfer_to_atlas_clicked
    self.master_layers(res, layer_type='atlas-overlay', color=[])
  File "C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py", line 4113, in master_layers
    self.layer_ctrl.layer_list[da_ind].set_thumbnail_data(res)
IndexError: list index out of range
