### ISSUE TITLE
How can I fix the rotation(yaw and pitch direction) I chose when I scroll along coronal sections? 

### ISSUE THREAD

**Issue by yqwang1** [JingyiGF/HERBS#34]
Hi,
is there a method to fix the rotation(yaw and pitch direction) I chose when I scroll along coronal sections? 
I found I needed to enter the rotation number every time I changed the sections, and it slowed me down in registering the slices.
and also I am wondering the number in the rotation means? like 1 means rotate how much degree?

Great thanks

**Comment by JingyiGF** [comment]
Hi, thanks for the feedback. I can fix it next week. I guess the 'yaw' and 'pitch' you mentioned means around x and y axis of the image. right? 

Ah, yes, you are totally correct, the unit for rotation angles are is degree. so 30 means 30 degree.

**Comment by JingyiGF** [comment]
Hi, Sorry for the late reply. I had been sick for some time. But I am now fixed it and updated the code on GitHub and PyPI v0.2.2. By checking the 'Keep Slice Angles' button, the angles will be remained after page number changed.

<img width="290" alt="Screenshot 2022-12-23 at 16 19 28" src="https://user-images.githubusercontent.com/64961126/209358958-67743994-0b32-472f-abde-ec70293fa2ee.png">

I will close this issue, Please do open a new issue if anything is not clear or anything is wrong.

Thank you for the request and wish you a happy holiday season! See you in 2023.
