### ISSUE TITLE
Unable to save project with virus objects

### ISSUE THREAD

**Issue by nataliekoh** [JingyiGF/HERBS#37]
I am getting the following error:

Traceback (most recent call last):
  File "C:\Users\---\AppData\Local\Continuum\anaconda3\envs\herbs\lib\site-packages\herbs\herbsgui.py", line 5532, in save_project_called
    data_2d = self.get_hist_single_layer_vis_data(single_layer_link)
  File "C:\Users\---\AppData\Local\Continuum\anaconda3\envs\herbs\lib\site-packages\herbs\herbsgui.py", line 5188, in get_hist_single_layer_vis_data
    pnt_vec = np.stack([temp[1], temp[0]], axis=1) + 0.5
IndexError: tuple index out of range

**Comment by JingyiGF** [comment]
Hi Natalie, Sorry for the late reply. I will check and come back to you on this. Which version are you using?

**Comment by nataliekoh** [comment]
Hi Jingyi, so glad to hear from you! 

Thank you! I am using Herbs 0.2.2.

**Comment by clementpouget** [comment]
Hi Jingyi, hi Natalie,

For future reference, I've been encountering the same issue with Herbs 0.2.2, both with a Python 3.8.10 and a Python 3.9.16 conda environment.

**Comment by AutomatedOlfactoryBehaviour** [comment]
I'm having the same issue on Win10 with Python 3.8.16 and Herbs 0.2.2.
Project saves without issue once the virus object removed.

Fingers crossed this can be solved because so far this has been the best registration/visualization tool I've come across!

**Comment by JingyiGF** [comment]
Thank you all for reporting this issue. Last week was Easter holiday in Norway, so I was not at work. I am in the process to update my operating system through University system( all files will be cleaned up afterwards), so I have to wait until IT guys finish this. Sorry for the delay. I will update you all after I have a working computer. And please do report other issues if any during this period.

**Comment by JingyiGF** [comment]
Hi, bug fixed in HERBS 0.2.3. Thank you all again for reporting this issue and waiting for so long! Please do let me know if there is further problems.
