### ISSUE TITLE
Can't install on Windows 11 with python>3.8

### ISSUE THREAD

**Issue by mwawra** [JingyiGF/HERBS#4]
Hi,
just in case anybody else run into the same problem.
When I tried to install HERBS on a Windows 11 PC (all updates) with Python 3.9.12 (from Anaconda3) I got a lot of errors like this:
```
      Checking to see if the QtCore bindings can be built...
      C:\Users\Matthias\anaconda3\Library\bin\qmake.exe QtCore.pro
      Project ERROR: Cannot run compiler 'cl'. Output:

      ===================

      ===================

      Maybe you forgot to setup the environment?
```

I think this is due to a missing prebuild of PyQT5 5.14.2 [https://pypi.org/project/PyQt5/5.14.2/#files](https://pypi.org/project/PyQt5/5.14.2/#files) for python versions above 3.8.
Beside installing Microsoft C/C++ Compiler and trying to build this package for newer a python version the easiest way is to use python 3.8. At least for me this worked perfectly fine.

**Comment by JingyiGF** [comment]
Hi, Many thanks for opening this issue, I will have a closer look and come back to this.

**Comment by JingyiGF** [comment]
Hi again, sorry for the late reply. We did not find a Windows 11 to be honest, but we have a Windows 10 which had exactly the error as what you had. We updated the dependencies and HERBS can be installed on the Windows 10 without any problems. Please let me know if you still have installation problem when updating/reinstalling HERBS.

**Comment by thecobb** [comment]
On windows 10 with python 3.8.10, an additional step I needed to take to get the installation working on a new conda environment (where I installed ipython and jupyter prior to installing Herbs) after manually installing PyQt5 to 5.14.2, was that I had to install PyQtGraph 0.12.3 since the version that was installed through Pip for Herbs (0.13.0) gave an error message and prevented the GUI from starting.

**Comment by JingyiGF** [comment]
Hi, Thank you for the feedback. you are right, I see the problem now. I limit PyQtGraph == 0.12.3 in HERBS 0.0.16 now.

**Comment by mwawra** [comment]
Hello, thanks for the taking care of this.
I tested it on Win 11 with a fresh conda env for python 3.8-3.10 and it worked without a problem.
So this seems to be fixed.
