### ISSUE TITLE
Unable to load probes or projects containing probes

### ISSUE THREAD

**Issue by AutomatedOlfactoryBehaviour** [JingyiGF/HERBS#40]
I've encountered a problem with loading probe objects.
Merged probe tracts were saved using _File_ -> _Save Object_ -> _probes_ without any error messages showing up in the console.
When loading the probes (_File_ -> _Load Objects_), the following error message is displayed in the console and nothing is loaded:
![image](https://user-images.githubusercontent.com/49727333/231319358-5dedb499-631c-4c18-b620-21be462590f1.png)

Possibly that's a simple typo as numpy has an attribute called "vstack" but not "vstck" and when changing the line that throws the error to "vstack" in the "herbsgui.py" file it does happily load the probes and so far I've found no issues when interacting with them (i.e. changing width, opacity, etc).

Unrelated to the first part, I also tried saving a project containing merged probe tracts through _File_ -> _Save Project_, again no error messages displayed when saving. When loading such a project (_File_ -> _Load Project_) it also loads the project and the contained probes with no error message.
Probes are shown on the Object Viewer Panel and the 3D panel and seem fine (i.e. the information pop-up also shows the correct details, they can be unmerged and merged again). However when viewing them in 3D and trying to change (i.e. their width, opacity, etc), errors appear. 
The following is the error when changing the width:
![image](https://user-images.githubusercontent.com/49727333/231367624-4e38326b-0e4c-4832-bb45-32670e169813.png)

The following is the error for changing opacity:
![image](https://user-images.githubusercontent.com/49727333/231367793-7e497f29-f648-47bc-8f33-e352980a7477.png)

The issues happen when running Herbs 0.2.2 on both Python 3.8.16 and 3.9.16 (on a Windows 10 machine with Anaconda 2.4.0).
Not sure if it's related to the issue I'm having when saving segmented fluorescence/[virus objects](https://github.com/JingyiGF/HERBS/issues/37) or if this is a separate issue.

Anyway, fingers crossed it's resolveable because so far I'm a very big fan :)

**Comment by JingyiGF** [comment]
Hi, thanks for reporting this issue. I will fix it next week. Last week was Easter holiday and this week I have no functional computer can be used. I will get my computer back next Monday. So will update you then.

**Comment by nataliekoh** [comment]
Also seeing this error with the same error message!

**Comment by JingyiGF** [comment]
Hi, bug fixed in HERBS 0.2.3. Thank you all again for reporting this issue and waiting for so long! Please do let me know if there is further problems.

**Comment by nataliekoh** [comment]
Hi Jingyi, it works now!! Thank you so much for fixing this!
