### ISSUE TITLE
Unable to load Allen Brain Atalas 

### ISSUE THREAD

**Issue by Chenyue-Doris** [JingyiGF/HERBS#50]
I had no problem installing and downloading herbs using the conda environment on Windows 10 (Python 3.9.0). However, I am having trouble when loading the Allen mice atlas

After I select a file in the file dialog to load the Allen atlas, there is no loading but a message showing "**Please pre-process boundary file**" (see attachment). 

Could you please help resolve this issue? Thank you!

![image](https://github.com/JingyiGF/HERBS/assets/128602308/8f78f10b-278c-48f7-9eb9-202b25446df0)

**Comment by JingyiGF** [comment]
Hi thank you for reporting the issue. My first thought is the pre-processing is not finished. Have you finished processing the downloaded atlas?

**Comment by Chenyue-Doris** [comment]
Hi thank you for answering. I think I should have finished processing the downloaded atlas. Here are the steps I took to download and process the atlas. Any advice would be appreciated. 

Firstly I click the "**Download**" button on the pop window and wait until the 2 green lines are complete. 
![image](https://github.com/JingyiGF/HERBS/assets/128602308/f95a9e11-f7fa-47b4-8d07-64e10ffb24aa)

Then I click "**Download Meshes**" and wait until the third green line is complete. 
![image](https://github.com/JingyiGF/HERBS/assets/128602308/037de4c3-3e4a-4ef5-9e01-869834941362)

Next, I click "**Process**" and wait until a fourth green is complete and a window pops up asking if I want to leave. There is no instruction for clicking "Process" in the Cookbook, but as it never changes after the completion of the three green lines, I have to click "Process" to proceed. 
![image](https://github.com/JingyiGF/HERBS/assets/128602308/b7801f29-805a-41ed-bd1e-cfcebab2dcdf)
![image](https://github.com/JingyiGF/HERBS/assets/128602308/f3f989a1-c36a-40a5-a929-217c51d8af5f)

**Comment by JingyiGF** [comment]
Thanks for the update. Yes, I can see that you have done the process. Could you please also show me how you load the atlas? For example I choose

![image](https://github.com/JingyiGF/HERBS/assets/64961126/0d625e4b-9813-492c-becf-f8943cd6cc4f)

then 

![image](https://github.com/JingyiGF/HERBS/assets/64961126/b33976ce-b5f1-4203-b799-ec05fe554e4a)

**Comment by Chenyue-Doris** [comment]
Hi thanks for your reply. Here is how I load the atlas.

As you have shown, I click "File" and choose "Load Atlas" in the dropdown list.
![image](https://github.com/JingyiGF/HERBS/assets/128602308/8b43a686-02b0-4833-ba29-5811f5ecf432)

Then I select a folder that I created to save the atlas
![image](https://github.com/JingyiGF/HERBS/assets/128602308/960ff0f2-5a7f-4742-a272-bc02f129b126)

After that, the error of "Please pre-process" boundary file appeared. 
![image](https://github.com/JingyiGF/HERBS/assets/128602308/91ee707d-d81e-47e1-9359-42703ad084e9)

**Comment by JingyiGF** [comment]
Hi, could you show me the files in your chosen folder? From the screenshot, I can see you chose the path c:\users\cren\herbs_data, I could not see any files or folders in the selected folder from your screenshot. If you see my screenshot, I have a waxholm_rat folder in my selected path, and in the waxholm_rat folder saved all my downloaded and processed atlas.Sent from my iPhoneOn 6 Oct 2023, at 14:21, Chenyue-Doris ***@***.***> wrote:﻿
Hi thanks for your reply. Here is how I load the atlas.
As you have shown, I click "File" and choose "Load Atlas" in the dropdown list.

Then I select a folder that I created to save the atlas

After that, the error of "Please pre-process" boundary file appeared.

**Comment by Chenyue-Doris** [comment]
Thank you so much for your answer. I resolved the issue by selecting the folder that saves all the downloaded and processed atlas.

**Comment by JingyiGF** [comment]
Great! Then I will close this issue. Please do not hesitate to contact us if you have any further questions.
